### PR TITLE
Updated snapshothelper file and removed info.plist from compiled output

### PR DESCRIPTION
**Pull request by chris-bidwrangler**
**Grabbed the latest snapshothelper file from:** [https://github.com/fastlane/fastlane/tree/master/snapshot](url)

**Grabbed the fix for the PLIST issue from:**
[https://github.com/fastlane-community/fastlane-plugin-cordova_screenshots/pull/26](url)

The fix for the unreleased swift version came over when the repo was forked.

### CODE REVIEW

**Comment by aharbick** [comment]
That’s a lot of changes...  did you make all of those changes or is the diff confused?

**Comment by chris-bidwrangler** [comment]
It looks like these are all the changes that I put in place.

The SnapshotHelper.swift file was outdated in this repo, so I grabbed the most recent file from the main Fastlane repo. You can accomplish the same changes by running `fastlane snapshot update`
but this will save us a step. 

The changes for the retrofit_cordova_screenshots_ios_action.rb file were pulled from a PR on the main repo that is waiting to be merged. Here is the issue - [https://github.com/fastlane-community/fastlane-plugin-cordova_screenshots/issues/25](url)

and here is a link to the diff for that PR - [https://github.com/fastlane-community/fastlane-plugin-cordova_screenshots/pull/26/files](url)

Without these changes I am getting the same error that is on the issue and the build fails in xcode:

`❌  error: Multiple commands produce '/var/folders/b8/zbn4kbds68d8s7_brr4yx3880000gn/T/snapshot_derived20191220-99448-1de3tt3/Build/Products/Debug-iphonesimulator/ui-snapshots-Runner.app/PlugIns/ui-snapshots.xctest/Info.plist':
`
` The Compile Sources build phase contains this target's Info.plist file '/src/my.project/my.bundle/fastlane/cordova_screenshots/ios/ui-snapshots/Info.plist'. (in target 'ui-snapshots' from project 'my.project')
    duplicate output file '/var/folders/b8/zbn4kbds68d8s7_brr4yx3880000gn/T/snapshot_derived20191220-99448-1de3tt3/Build/Products/Debug-iphonesimulator/ui-snapshots-Runner.app/PlugIns/ui-snapshots.xctest/Info.plist' on task: ProcessInfoPlistFile /var/folders/b8/zbn4kbds68d8s7_brr4yx3880000gn/T/snapshot_derived20191220-99448-1de3tt3/Build/Products/Debug-iphonesimulator/ui-snapshots-Runner.app/PlugIns/ui-snapshots.xctest/Info.plist /src/my.project/my.bundle/fastlane/cordova_screenshots/ios/ui-snapshots/Info.plist (in target 'ui-snapshots' from project 'my.project')
Testing failed:`

**Comment by aharbick** [comment]
I see.  Those seem fine.

**Review by aharbick — APPROVED** [review]
Thanks for the explanations.

**Comment by chris-bidwrangler** [comment]
I wish I had reached out (or found those docs ) earlier. Would have saved a few dents in my head from banging it on my desk. Thanks @aharbick 

Was a simple fix to get the MTC disabled. I just added a commit for this but was pretty straightforward:

`launch_action = scheme.instance_variable_get :@launch_action
launch_action.disable_main_thread_checker=true
test_action = scheme.instance_variable_get :@test_action
 test_action.disable_main_thread_checker=true`

Also, added my UI Tests.

**Pull request merged**
